### ISSUE TITLE
unresponsive main thread godot 

### ISSUE THREAD

**Issue by Ehsanwww** [V-Sekai/v-sekai.whisper#16]
Hello everyone, 
thanks for this plugin; when I run projects in godot, main thread of godot got unresponsive and and also the result is not good enough, I do multi threading but nothing changed; can run whisper real time? i noticed much of latency @Ughuuu @fire @TokageItLab

**Comment by Ughuuu** [comment]
Its still wip, not yet released. What model u using, os, godot, etc? how long the sound?

**Comment by Ughuuu** [comment]
You can reopen if you want after we release. Consider this repo as alpha state for now.
